### PR TITLE
Update to JDK11

### PR DESCRIPTION
**Pull request by big-andy-coates**
**Breaking change**: Dropping support for Java8 is a breaking change for anyone using Java8. I recommend bumping the major version.

Updates tool chain to Java 11 (LTS), and updates the JGit dependency to the latest (which requires J11). This [highlighted](https://github.com/allegro/axion-release-plugin/actions/runs/4128657832/jobs/7133366021) issue https://github.com/allegro/axion-release-plugin/issues/573 until the [fix](https://github.com/allegro/axion-release-plugin/pull/575) was merged.

Updating JGIt to the latest version also highlighted and issue with a package name change for classes in the `org.eclipse.jgit:org.eclipse.jgit.ssh.jsch` dependency: both `JschConfigSessionFactory` and `OpenSshConfig` referenced from `SshConnector` have moved between JGit version 5.x.x and 6.x.x.

 **Implications**: users of the current plugin with a Gradle build environment that's pulling JGit 6.x.x will likely encounter `ClassNotFound` style errors if using the `SshConnector` class.

Build is now green.

### CODE REVIEW

**Comment by big-andy-coates** [comment]
Hummm... looks like the build is now failing because of another plugin not being compatible with J11:

```
> There was a failure while executing work items
   > A failure occurred while executing org.gradle.plugin.devel.tasks.internal.ValidateAction
      > pl/allegro/tech/build/axion/release/TagPrefixConf has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Bumping `com.gradle.plugin-publish` to the latest `1.1.0`

**Comment by big-andy-coates** [comment]
@bgalek ready for review :)

**Comment by bgalek** [comment]
I just released 14.4.0 and added release notes that we'll be preparing axion@2.0 with jdk11 as base ;)

**Comment by big-andy-coates** [comment]
Yep, I saw 🚀  :)

**Comment by bgalek** [comment]
I've created `v1` branch as a backport to support jdk8

**Pull request merged**
