### PR TITLE
Test reports as artifacts

### PR DESCRIPTION
**Pull request by kkocel**

### CODE REVIEW

**Comment by bgalek** [comment]
hi @kkocel, why do we need to persist test result artifact?

**Comment by kkocel** [comment]
there is no need, only possiblity :) 
having access to reports you are able to see the whole stacktrace and standard output (which is not possible with test-report plugin)

**Comment by kkocel** [comment]
if you don't think it's needed feel free to close/reject the PR :)

**Comment by bgalek** [comment]
maybe gradle --scan would be better than?

**Pull request closed without merging**
