### PR TITLE
#212 fix incorrect version after release when using markNextVersion a…

### LINKED ISSUE #212: useHighestVersion and markNextVersion don't work correctly together
The resolved version is incorrect after doing a release based on a next version marker when using useHighestVersion. It uses the next snapshot version instead of the current release version, making it impossible to publish the release with the correct version number.

Reproduction steps:
```
# ./gradlew cV
0.1.1-SNAPSHOT
# ./gradlew markNextVersion -Prelease.version=1.0.0
# git commit -m 'some work' --allow-empty
# ./gradlew release
# ./gradlew cV
1.0.1-SNAPSHOT // should be 1.0.0
```
The git log looks like this at this point:
```
cad6ee7 (tag: release-1.0.0) some work
d2c5794 (tag: release-1.0.0-alpha) set useHighestVersion to true
0567f21 (tag: release-0.1.0) initial commit with axion-release 1.8.1
```

### PR DESCRIPTION
**Pull request by cliffred**
Fixes #212

### CODE REVIEW

**Comment by adamdubiel** [comment]
Thanks for the fix!

I analysed the problem just to understand it better. From what i see if there are two commits which resolve to the same version (as in 1.1.0 and 1.1.0-alpha) commit metadata is taken from earlier one. In this case it is -alpha. Commit metadata, namely `isHead` property is crucial when determining if it is a snapshot or release. Taking `isHead` from wrong commit results in this bug.

**Comment by cliffred** [comment]
That's exactly right. The fix just makes sure that whenever a final and alpha exist for the same version, the final is always regarded as newer.

**Comment by adamdubiel** [comment]
Merged :) Plus i added a commit with short comment on this logic.

Would you like me to release this fix asap, or can i take my time to fix the other problem you reported (push fails with auth problems)?

**Comment by cliffred** [comment]
Thanks :)
It can wait. We can work around this issue by deleting the alpha tag.

**Pull request merged**
