### PR TITLE
Make configuration Kotlin DSL friendly

### PR DESCRIPTION
**Pull request by cloudshiftchris**
Implementation making configuration Kotlin DSL friendly.

Addresses specific issues in #449 as well as a full review, remediation of all configuration to be Kotlin DSL compatible.

### CODE REVIEW

**Comment by bgalek** [comment]
I've given it a quick look - nice job! 
I'll check it out more in max few days, and I hope will merge that!

**Comment by bgalek** [comment]
@cloudshiftchris could you also update the /docs folder? :)

**Comment by cloudshiftchris** [comment]
@bgalek docs updated!  Added a section under Examples showing a full example; in most cases, the Groovy syntax will work just fine (accounting for Kotlin differences like required parens, double quotes).

**Comment by bgalek** [comment]
@cloudshiftchris that was quick! :) It really looks nice, let me test it last time and I'll be happy to release it!

**Comment by bgalek** [comment]
@cloudshiftchris plugin release fails with error "Invalid plugin ID 'pl.***.tech.build.axion-release': multiple plugins are using the same ID" wanna check it out?

**Comment by bgalek** [comment]
@cloudshiftchris never mind, fixed ;)

**Comment by bgalek** [comment]
@cloudshiftchris thx for your support, I've released new version - care to test it last time? :)

**Comment by cloudshiftchris** [comment]
@bgalek works good, thanks for the release!  Able to remove janky adapter code, back to equivalent with Groovy:

```
scmVersion {
    localOnly = true
    tag {
        prefix = "release"
        versionSeparator = "/"
    }
}
```

**Pull request merged**
