### PR TITLE
feat: enable snapshot customization

### PR DESCRIPTION
**Pull request by pwielgolaski**
using similar mechanism as with versionCreator, user can provider closure snapshotCreator
closure gives full freedom to customize snapshot i.e. as timestamp

it is addressing https://github.com/allegro/axion-release-plugin/issues/327

### CODE REVIEW

**Comment by bgalek** [comment]
hi @pwielgolaski! I'll look at this this week - it seems to be a small change, should be easy to review ;)

**Review by bgalek — APPROVED** [review]

**Comment by bgalek** [comment]
@pwielgolaski LGTM :) could you also update the docs? :)

**Comment by pwielgolaski** [comment]
@bgalek I added documentation piece, hope you find it sufficient.
If you expect something else, let me know

**Review by bgalek — APPROVED** [review]

**Comment by bgalek** [comment]
@pwielgolaski nope, seems legit! I'll release it tommorow :)

**Pull request merged**
