### PR TITLE
Chooses normal version over nextVersion when both on same commit

### PR DESCRIPTION
**Pull request by adamdubiel**
Solves #85

### CODE REVIEW

**Comment by MrException** [comment]
Is it possible that this will also solve #196?

**Comment by adamdubiel** [comment]
Yes, this is probably it :)

**Comment by MrException** [comment]
What's the easiest way to test that? Is there a snapshot of the plugin or something that I can point my project at?

Any ideas when a 1.8.0 release will be ready to go? Can this fix go into a 1.7.2 version possibly?

**Comment by adamdubiel** [comment]
I got tied up into performance optimizations, but i guess i should make 1.7.2 available earlier. I hope to have some time to work on this this week - is it ok with you?

**Comment by MrException** [comment]
That would be awesome @adamdubiel!

Thanks for your work on this plugin! We're using it quite a bit on our projects now, it's been working out great.

**Comment by adamdubiel** [comment]
I'm happy to hear that :)

**Pull request merged**
